import type { Metadata } from "next";
import "./design-system/tailwind.css";
import "./base.css";

export const metadata: Metadata = {
  title: "Kayla || Product designer",
  description: "Generated by create next app",
  other: {
    "apple-mobile-web-app-title": "ks.design",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
